using System.Collections.Generic;
using Godot;
using UnnamedRTS.Core;

namespace UnnamedRTS.Systems.Networking;

/// <summary>
/// Pre-game lobby managing player slots, faction selection, ready state, and match start.
/// The host is authoritative: faction uniqueness and match start are enforced server-side.
/// All state changes are broadcast via Godot RPC to keep all clients in sync.
/// </summary>
public partial class LobbyManager : Node
{
    /// <summary>Maximum player slots (one per faction).</summary>
    public const int MaxSlots = 6;

    /// <summary>Player slots keyed by player ID (0–5) for deterministic iteration.</summary>
    private readonly SortedList<int, PlayerSlot> _playerSlots = new();

    /// <summary>Selected map identifier. Only the host can change this.</summary>
    public string SelectedMap { get; private set; } = "";

    /// <summary>Match seed generated by host and distributed to all clients.</summary>
    public ulong MatchSeed { get; private set; }

    /// <summary>Whether this client is the host.</summary>
    public bool IsHost { get; private set; }

    /// <summary>This client's player ID in the lobby.</summary>
    public int LocalPlayerId { get; private set; }

    private NetworkTransport? _transport;

    // Map from Godot multiplayer peer ID → lobby player ID
    private readonly SortedList<int, int> _peerToPlayerId = new();
    private int _nextPlayerId;

    /// <summary>
    /// Returns all current player slots (read-only access).
    /// </summary>
    public SortedList<int, PlayerSlot> GetPlayerSlots() => _playerSlots;

    // ── Initialization ──────────────────────────────────────────────

    /// <summary>
    /// Sets up the lobby for the host. The host is automatically added as player 0.
    /// </summary>
    public void InitializeAsHost(NetworkTransport transport, string playerName)
    {
        _transport = transport;
        IsHost = true;
        _nextPlayerId = 0;
        _playerSlots.Clear();
        _peerToPlayerId.Clear();

        LocalPlayerId = _nextPlayerId++;
        _peerToPlayerId[transport.LocalPeerId] = LocalPlayerId;

        var slot = new PlayerSlot
        {
            PlayerId = LocalPlayerId,
            PlayerName = playerName,
            FactionId = "",
            IsReady = false,
            IsHost = true
        };
        _playerSlots[LocalPlayerId] = slot;

        transport.PeerConnected += OnPeerConnected;
        transport.PeerDisconnected += OnPeerDisconnected;

        GD.Print($"[LobbyManager] Host lobby created. Player '{playerName}' is player {LocalPlayerId}.");
    }

    /// <summary>
    /// Sets up the lobby for a client. The client announces itself to the host.
    /// </summary>
    public void InitializeAsClient(NetworkTransport transport, string playerName)
    {
        _transport = transport;
        IsHost = false;
        _playerSlots.Clear();
        _peerToPlayerId.Clear();

        transport.PeerConnected += OnPeerConnected;
        transport.PeerDisconnected += OnPeerDisconnected;

        // Announce to host — the host will assign a player ID and broadcast back
        RpcId(1, MethodName.ServerRequestJoin, playerName);

        GD.Print($"[LobbyManager] Client requesting to join as '{playerName}'.");
    }

    // ── Client-callable actions ─────────────────────────────────────

    /// <summary>
    /// Request to select a faction. Returns false if taken (host enforced).
    /// </summary>
    public void RequestSelectFaction(string factionId)
    {
        if (IsHost)
        {
            TrySelectFaction(LocalPlayerId, factionId);
        }
        else
        {
            RpcId(1, MethodName.ServerRequestFaction, LocalPlayerId, factionId);
        }
    }

    /// <summary>
    /// Toggle ready state for this player.
    /// </summary>
    public void RequestSetReady(bool ready)
    {
        if (IsHost)
        {
            SetPlayerReady(LocalPlayerId, ready);
        }
        else
        {
            RpcId(1, MethodName.ServerRequestReady, LocalPlayerId, ready);
        }
    }

    /// <summary>
    /// Sets the map (host only).
    /// </summary>
    public void SetMap(string mapId)
    {
        if (!IsHost) return;
        SelectedMap = mapId;
        Rpc(MethodName.ClientOnMapChanged, mapId);
    }

    /// <summary>
    /// Returns true if all players are ready and there are at least 2 players.
    /// </summary>
    public bool AllPlayersReady()
    {
        if (_playerSlots.Count < 2) return false;

        for (int i = 0; i < _playerSlots.Count; i++)
        {
            if (!_playerSlots.Values[i].IsReady)
                return false;
        }
        return true;
    }

    /// <summary>
    /// Host starts the match: generates seed and broadcasts start signal.
    /// </summary>
    public void StartMatch()
    {
        if (!IsHost) return;
        if (!AllPlayersReady()) return;

        // Generate a match seed from system time (non-deterministic source is fine here —
        // it's used to SEED the deterministic RNG, and all clients receive the same seed)
        MatchSeed = (ulong)System.DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();

        GD.Print($"[LobbyManager] Starting match with seed {MatchSeed}, map '{SelectedMap}', {_playerSlots.Count} players.");
        Rpc(MethodName.ClientOnMatchStart, MatchSeed, SelectedMap);

        // Also trigger locally
        OnMatchStartLocal(MatchSeed, SelectedMap);
    }

    /// <summary>
    /// Cleans up lobby state and event subscriptions.
    /// </summary>
    public void Shutdown()
    {
        if (_transport != null)
        {
            _transport.PeerConnected -= OnPeerConnected;
            _transport.PeerDisconnected -= OnPeerDisconnected;
            _transport = null;
        }
        _playerSlots.Clear();
        _peerToPlayerId.Clear();
    }

    // ── Server-side RPCs (called by clients, run on host) ──────────

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ServerRequestJoin(string playerName)
    {
        if (!IsHost) return;
        int senderId = Multiplayer.GetRemoteSenderId();

        if (_playerSlots.Count >= MaxSlots)
        {
            GD.PushWarning($"[LobbyManager] Rejecting player '{playerName}' — lobby full.");
            return;
        }

        int playerId = _nextPlayerId++;
        _peerToPlayerId[senderId] = playerId;

        var slot = new PlayerSlot
        {
            PlayerId = playerId,
            PlayerName = playerName,
            FactionId = "",
            IsReady = false,
            IsHost = false
        };
        _playerSlots[playerId] = slot;

        // Send the full lobby state to the new player
        for (int i = 0; i < _playerSlots.Count; i++)
        {
            var existing = _playerSlots.Values[i];
            RpcId(senderId, MethodName.ClientOnPlayerJoined,
                existing.PlayerId, existing.PlayerName, existing.FactionId, existing.IsReady, existing.IsHost);
        }

        // Tell the new player their assigned ID
        RpcId(senderId, MethodName.ClientOnAssignedId, playerId);

        // Broadcast the new player to everyone else
        Rpc(MethodName.ClientOnPlayerJoined, playerId, playerName, "", false, false);

        // Notify map selection
        if (!string.IsNullOrEmpty(SelectedMap))
        {
            RpcId(senderId, MethodName.ClientOnMapChanged, SelectedMap);
        }

        EventBus.Instance?.EmitPlayerConnected(playerId, playerName);
        EventBus.Instance?.EmitLobbyUpdated();
        GD.Print($"[LobbyManager] Player '{playerName}' joined as player {playerId}.");
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ServerRequestFaction(int playerId, string factionId)
    {
        if (!IsHost) return;
        TrySelectFaction(playerId, factionId);
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ServerRequestReady(int playerId, bool ready)
    {
        if (!IsHost) return;
        SetPlayerReady(playerId, ready);
    }

    // ── Client-side RPCs (called by host, run on clients) ──────────

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnAssignedId(int playerId)
    {
        LocalPlayerId = playerId;
        GD.Print($"[LobbyManager] Assigned player ID: {playerId}");
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnPlayerJoined(int playerId, string playerName, string factionId, bool isReady, bool isHost)
    {
        var slot = new PlayerSlot
        {
            PlayerId = playerId,
            PlayerName = playerName,
            FactionId = factionId,
            IsReady = isReady,
            IsHost = isHost
        };
        _playerSlots[playerId] = slot;
        EventBus.Instance?.EmitLobbyUpdated();
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnPlayerLeft(int playerId)
    {
        if (_playerSlots.ContainsKey(playerId))
        {
            _playerSlots.Remove(playerId);
        }
        EventBus.Instance?.EmitPlayerDisconnected(playerId);
        EventBus.Instance?.EmitLobbyUpdated();
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnFactionSelected(int playerId, string factionId)
    {
        if (_playerSlots.TryGetValue(playerId, out var slot))
        {
            slot.FactionId = factionId;
            _playerSlots[playerId] = slot;
        }
        EventBus.Instance?.EmitLobbyUpdated();
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnReadyChanged(int playerId, bool ready)
    {
        if (_playerSlots.TryGetValue(playerId, out var slot))
        {
            slot.IsReady = ready;
            _playerSlots[playerId] = slot;
        }
        EventBus.Instance?.EmitLobbyUpdated();
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnMapChanged(string mapId)
    {
        SelectedMap = mapId;
        EventBus.Instance?.EmitLobbyUpdated();
    }

    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    private void ClientOnMatchStart(ulong seed, string mapId)
    {
        OnMatchStartLocal(seed, mapId);
    }

    // ── Internal helpers ───────────────────────────────────────────

    private void OnPeerConnected(long peerId)
    {
        // Handled by ServerRequestJoin when the client sends its name
    }

    private void OnPeerDisconnected(long peerId)
    {
        int intPeerId = (int)peerId;
        if (_peerToPlayerId.TryGetValue(intPeerId, out int playerId))
        {
            _peerToPlayerId.Remove(intPeerId);

            if (_playerSlots.ContainsKey(playerId))
            {
                string name = _playerSlots[playerId].PlayerName;
                _playerSlots.Remove(playerId);

                if (IsHost)
                {
                    Rpc(MethodName.ClientOnPlayerLeft, playerId);
                }

                EventBus.Instance?.EmitPlayerDisconnected(playerId);
                EventBus.Instance?.EmitLobbyUpdated();
                GD.Print($"[LobbyManager] Player {playerId} ('{name}') disconnected.");
            }
        }
    }

    private void TrySelectFaction(int playerId, string factionId)
    {
        if (!_playerSlots.ContainsKey(playerId)) return;

        // Check uniqueness — no two players can have the same faction
        if (!string.IsNullOrEmpty(factionId))
        {
            for (int i = 0; i < _playerSlots.Count; i++)
            {
                var existing = _playerSlots.Values[i];
                if (existing.PlayerId != playerId && existing.FactionId == factionId)
                {
                    GD.Print($"[LobbyManager] Faction '{factionId}' already taken by player {existing.PlayerId}.");
                    return;
                }
            }
        }

        var slot = _playerSlots[playerId];
        slot.FactionId = factionId;
        _playerSlots[playerId] = slot;

        // Broadcast to all
        Rpc(MethodName.ClientOnFactionSelected, playerId, factionId);
        // Also apply locally on host
        EventBus.Instance?.EmitLobbyUpdated();
    }

    private void SetPlayerReady(int playerId, bool ready)
    {
        if (!_playerSlots.ContainsKey(playerId)) return;

        var slot = _playerSlots[playerId];
        slot.IsReady = ready;
        _playerSlots[playerId] = slot;

        Rpc(MethodName.ClientOnReadyChanged, playerId, ready);
        EventBus.Instance?.EmitLobbyUpdated();
    }

    private void OnMatchStartLocal(ulong seed, string mapId)
    {
        MatchSeed = seed;
        SelectedMap = mapId;
        GD.Print($"[LobbyManager] Match starting — seed={seed}, map='{mapId}'");
        EventBus.Instance?.EmitMatchCountdown(3);
    }
}

/// <summary>
/// Represents one player slot in the pre-game lobby.
/// </summary>
public struct PlayerSlot
{
    public int PlayerId;
    public string PlayerName;
    public string FactionId;
    public bool IsReady;
    public bool IsHost;
}
