#!/usr/bin/env bash
# build-linux.sh — Export Linux binary and build Snap package
# Generated by generate_versions.py — do not edit directly.
#
# Prerequisites:
#   - $GODOT4 points to Godot 4.4 headless binary
#   - snapcraft CLI available (sudo snap install snapcraft --classic)
#   - Linux/X11 export templates installed

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build/linux"
DIST_DIR="$PROJECT_ROOT/dist/linux"
GODOT="${GODOT4:-godot4}"

echo "=== Cordite Wars: Linux Build ==="

mkdir -p "$BUILD_DIR" "$DIST_DIR"

# 1. Export from Godot
echo "--- Exporting Linux binary..."
cd "$PROJECT_ROOT"
"$GODOT" --headless --export-release "Linux/X11" "$BUILD_DIR/CorditeWars"

if [ ! -f "$BUILD_DIR/CorditeWars" ]; then
  echo "ERROR: Godot export failed."
  exit 1
fi

chmod +x "$BUILD_DIR/CorditeWars"
echo "--- Export complete: $BUILD_DIR/CorditeWars"

# 2. Build Snap package
echo "--- Building Snap package..."
cd "$PROJECT_ROOT"
snapcraft --destructive-mode

SNAP_FILE=$(ls cordite-wars_*.snap 2>/dev/null | head -1)
if [ -n "$SNAP_FILE" ]; then
  mv "$SNAP_FILE" "$DIST_DIR/"
  echo "--- Snap built: $DIST_DIR/$SNAP_FILE"
else
  echo "WARNING: snapcraft did not produce a .snap file. Check build output."
fi

echo "=== Linux build complete ==="
