#!/usr/bin/env bash
# build-macos.sh — Export macOS app, sign, create DMG, and notarize
# Generated by generate_versions.py — do not edit directly.
#
# Prerequisites:
#   - Xcode 14+ and Command Line Tools installed
#   - Apple Developer Program membership
#   - $GODOT4 points to Godot 4.4 headless binary
#   - macOS export templates installed
#   - Environment variables set:
#       APPLE_DEV_ID    — "Developer ID Application: Your Name (TEAMID)"
#       APPLE_TEAM_ID   — 10-character team identifier
#       APPLE_ID        — your Apple ID email
#       AC_PASSWORD     — App-Specific Password (create at appleid.apple.com)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build/macos"
DIST_DIR="$PROJECT_ROOT/dist/macos"
GODOT="${GODOT4:-godot4}"
APP_BUNDLE="$BUILD_DIR/CorditeWars.app"
DMG_PATH="$DIST_DIR/CorditeWars_0.1.0.dmg"

# Required env vars
: "${APPLE_DEV_ID:?APPLE_DEV_ID not set}"
: "${APPLE_TEAM_ID:?APPLE_TEAM_ID not set}"
: "${APPLE_ID:?APPLE_ID not set}"
: "${AC_PASSWORD:?AC_PASSWORD not set}"

echo "=== Cordite Wars: macOS Build ==="

mkdir -p "$BUILD_DIR" "$DIST_DIR"

# ── Step 1: Export from Godot ──────────────────────────────────────────────
echo "--- Exporting macOS app bundle..."
cd "$PROJECT_ROOT"
"$GODOT" --headless --export-release "macOS" "$APP_BUNDLE"

if [ ! -d "$APP_BUNDLE" ]; then
  echo "ERROR: Godot export did not produce $APP_BUNDLE"
  exit 1
fi

# ── Step 2: Code sign ─────────────────────────────────────────────────────
echo "--- Signing app bundle..."
codesign --deep --force --options runtime \
  --entitlements "$PROJECT_ROOT/versions/macos/entitlements.plist" \
  --sign "$APPLE_DEV_ID" \
  --timestamp \
  "$APP_BUNDLE"

echo "--- Verifying signature..."
codesign --verify --deep --strict --verbose=2 "$APP_BUNDLE"
spctl --assess --type execute --verbose "$APP_BUNDLE" || echo "NOTE: spctl may fail on dev machine before notarization."

# ── Step 3: Create DMG ────────────────────────────────────────────────────
echo "--- Creating DMG..."
hdiutil create \
  -volname "Cordite Wars" \
  -srcfolder "$APP_BUNDLE" \
  -ov \
  -format UDZO \
  "$DMG_PATH"

codesign --sign "$APPLE_DEV_ID" --timestamp "$DMG_PATH"

# ── Step 4: Submit for notarization ───────────────────────────────────────
echo "--- Submitting for notarization (this may take a few minutes)..."
xcrun notarytool submit "$DMG_PATH" \
  --apple-id "$APPLE_ID" \
  --team-id "$APPLE_TEAM_ID" \
  --password "$AC_PASSWORD" \
  --wait

# ── Step 5: Staple the notarization ticket ────────────────────────────────
echo "--- Stapling notarization ticket..."
xcrun stapler staple "$DMG_PATH"
xcrun stapler validate "$DMG_PATH"

echo "=== macOS build complete ==="
echo "Distributable: $DMG_PATH"
