namespace CorditeWars.Core.Licensing;

/// <summary>
/// Static configuration for the in-game licensing system.
///
/// The <see cref="LicenseSigningPublicKey"/> below is a placeholder that
/// disables the licensing gate when checked in to source control. Production
/// builds replace it with the real 32-byte Ed25519 public key generated by
/// <c>tools/license_keygen.py generate-signing-key</c> (the
/// <c>public_key_raw_hex</c> output).
///
/// While the placeholder is in place:
///   * The bootloader skips the licensing gate entirely.
///   * No network calls are made.
///   * The game runs identically to a pre-licensing build.
///
/// This keeps the source tree DRM-free for contributors building from source,
/// while still letting the release pipeline drop in the production key for
/// official builds.
///
/// To enable for a release, replace the all-zero array below with the real
/// 32 bytes (one place to edit, no other code changes required).
/// </summary>
public static class LicenseConfig
{
    /// <summary>
    /// Raw 32-byte Ed25519 public key matching the private key held in
    /// AWS Secrets Manager at <c>&lt;bucket&gt;/license-signing</c>.
    /// </summary>
    public static readonly byte[] LicenseSigningPublicKey = new byte[32]; // all zeros = disabled

    /// <summary>
    /// HTTPS base URL of the licensing API, e.g. <c>https://downloads.example.com</c>.
    /// The gate appends <c>/api/activate</c> etc.
    /// </summary>
    public const string ApiBaseUrl = "https://downloads.koshkikode.com";

    /// <summary>True when a real public key has been baked in for this build.</summary>
    public static bool IsEnabled
    {
        get
        {
            foreach (byte b in LicenseSigningPublicKey)
            {
                if (b != 0) return true;
            }
            return false;
        }
    }
}
